inherit_mode:
  Include:
    - Include
    - Exclude
    - inherit_gem
    - plugins
    - requires

inherit_from:
  - shopify.yml
  - rspec.yml
  - performance.yml
  - thread_safety.yml

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  Exclude:
    - bin/**/*.rb
    - sig/generated/**/*.rb
    - tmp/**/*.rb
    - vendor/**/*.rb

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/Alias:
  EnforcedStyle: prefer_alias

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: require_parentheses

Style/SymbolProc:
  Enabled: false

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true
